FROM fransking/flink-statefun:3.4-SNAPSHOT

RUN mkdir -p /opt/statefun/modules/embedded
COPY flink-statefun-tasks-embedded/statefun-tasks-distribution/target/statefun-tasks-distribution-3.4-SNAPSHOT.jar /opt/statefun/modules/embedded/
