FROM fransking/flink-statefun:3.4.0

RUN mkdir -p /opt/statefun/modules/embedded
COPY flink-statefun-tasks-embedded/statefun-tasks-distribution/target/statefun-tasks-distribution-3.4.0.jar /opt/statefun/modules/embedded/
